server:
  point_cloud_sampling_stride: 20 
  local_point_cloud_voxel_downsampling: 0.02 
  global_point_cloud_voxel_dowsampling: 0.03
  data_root: "/media/ai/T7/agco2026/"
  chunk_size: 200000
  annotation_file: "bboxes.json"
  coord_dir_name: "pointcloud_raw"
  lidar_types: ["lslidar","rslidar","ouster"]
  max_cache_size: 500

frontend: 
  label_dict:
    background: 0
    tractor: 1
    harvester: 2
    trailer: 3
    car: 4 
    building: 5 
    tree: 6






